# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy application files into the container
COPY app.py logic.py requirements.txt ./

# Create logs directory inside the container
RUN mkdir logs

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for Flask
EXPOSE 5000

# Set an environment variable for the app's base directory
ENV APP_BASE_DIR=/app

# Run the Flask app
CMD ["python", "app.py"]
