services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 on your host to port 5000 in the container
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=mydatabase
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meme
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map port 5432 on your host to port 5432 in the container

volumes:
  postgres_data:
