version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: python_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5000:5000"
    depends_on:
      - db

  curl:
    image: curlimages/curl:latest
    container_name: curl_client
    depends_on:
      - app
    entrypoint: ["/bin/sh", "-c"]
    command: "tail -f /dev/null"  # Keeps the container running
